server:
  port: 8085

spring:
  profiles:
    active: prod

  application:
    name: demographie-microservice

  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://configserver:9999}

  datasource:
    url: jdbc:h2:mem:demodb

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  cloud:
    config:
      enabled: true
      fail-fast: false
    discovery:
      enabled: true

  # ✅ eureka doit être à la racine (même niveau que spring et server)
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL}   # ← ÇA SEUL
    register-with-eureka: true
    fetch-registry: true
    enabled: true
  instance:
    prefer-ip-address: true
    hostname: medicament-ms
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: '*'

build:
  version: 1.0

author:
  name: "malek Demographie"
  email: "malek_Demographie2003@gmail.com"
