spring:
  application:
    name: configserver
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/malekbacouch90210/config-repo
          default-label: main
          clone-on-start: true
#        native:
          # search-locations: "classpath:/config"
#          search-locations: file:///D:/Cours IT/IntelliJ_Idea workspace/Spring/Spring_cloud/malek-spring-cloud/config-repo


server:
  port: 9999
