services:
  eurekaserver:
    build: ./eurekaserver
    container_name: eurekaserver
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8761/actuator/health"]
      interval: 10s

  configserver:
    build: ./configserver
    container_name: configserver
    ports:
      - "9999:9999"
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:9999/actuator/health"]
      interval: 10s

  demographies-ms:
    build: ./demographie-microservice
    container_name: demographies-ms
    ports:
      - "8085:8085"
    environment:
      DISCOVERY_SERVICE_URL: http://eurekaserver:8761/eureka
      CONFIG_SERVICE_URL: http://configserver:9999
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
